resources:
- name: repo
  type: git
  source:
    uri: https://github.com/SanketShah-21/ConcourseTest.git
    branch: main
    private_key: |  
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
      QyNTUxOQAAACAE3a5F1BtT7DdIEbv+3NdSBVUdwWxc6bsVWZVlxz1AwwAAAJj7vXd8+713
      fAAAAAtzc2gtZWQyNTUxOQAAACAE3a5F1BtT7DdIEbv+3NdSBVUdwWxc6bsVWZVlxz1Aww
      AAAEAB3NKrZ82gqa8aZNrLb7Pj+F7hRUdYIAWpMgGdnXICZQTdrkXUG1PsN0gRu/7c11IF
      VR3BbFzpuxVZlWXHPUDDAAAAEnNzaGFoQGNhcmd1cnVzLmNvbQECAw==
      -----END OPENSSH PRIVATE KEY-----

jobs:
- name: hello-world-job-8
  plan:
  - get: repo
    trigger: true   # tell Concourse to trigger this job when new versions are emitted
  - task: create-commit
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: gitea/gitea
      inputs:
      - name: repo
      outputs:
      - name: repo
      params:
        EMAIL: sshah@cargurus.com
      run:
        path: sh
        args:
        - -cx
        # this is just a bash script
        - |
          cd repo
          date +%Y-%m-%d > todays-date
          git add ./todays-date
          git config --global user.email $EMAIL
          git config --global user.name $GIT_AUTHOR_NAME
          git commit -m "Yoo! Updated todays date"
  - put: repo
    params:
      repository: repo
